### ISSUE TITLE
(question) how to use meteor + apollo with nova

### ISSUE THREAD

**Issue by freeseamew** [kaviarjs/nova#25]
It is currently testing nova in a meteor + apollo environment.

The error below is shown.

```
=> Modified -- restarting.
W20201217-10:55:28.209(9)? (STDERR) /Users/gimgeun-yeong/.meteor/packages/meteor-tool/.1.12.0.1vqv652.8etjg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20201217-10:55:28.210(9)? (STDERR)                                             throw(ex);
W20201217-10:55:28.210(9)? (STDERR)                                             ^
W20201217-10:55:28.211(9)? (STDERR) 
W20201217-10:55:28.211(9)? (STDERR) TypeError: this._maybeSetUpReplication is not a function
W20201217-10:55:28.212(9)? (STDERR)     at Object.Collection (packages/mongo/collection.js:109:8)
W20201217-10:55:28.212(9)? (STDERR)     at module (imports/api/collections/index.js:6:22)
W20201217-10:55:28.212(9)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201217-10:55:28.212(9)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201217-10:55:28.213(9)? (STDERR)     at Module.moduleLink [as link] (/Users/gimgeun-yeong/.meteor/packages/modules/.0.15.0.4vy2br.hr50n++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201217-10:55:28.213(9)? (STDERR)     at module (imports/apollo/resolver.js:1:42)
W20201217-10:55:28.213(9)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201217-10:55:28.213(9)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201217-10:55:28.213(9)? (STDERR)     at Module.moduleLink [as link] (/Users/gimgeun-yeong/.meteor/packages/modules/.0.15.0.4vy2br.hr50n++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201217-10:55:28.213(9)? (STDERR)     at module (imports/startup/server/index.js:1:540)
W20201217-10:55:28.214(9)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201217-10:55:28.214(9)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201217-10:55:28.215(9)? (STDERR)     at Module.moduleLink [as link] (/Users/gimgeun-yeong/.meteor/packages/modules/.0.15.0.4vy2br.hr50n++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201217-10:55:28.215(9)? (STDERR)     at module (server/index.js:1:8)
W20201217-10:55:28.215(9)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201217-10:55:28.215(9)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
```

The code is as follows.

- imports/api/collection

```
import { Mongo } from 'meteor/mongo';

const Category = new Mongo.Collection('category')
const Goods = new Mongo.Collection('goods');
const Vendor = Mongo.Collection('vendor');

export {
  Category,
  Goods,
  Vendor
}
```
- imports/apollo/schema.js
```
import { gql } from 'apollo-server';


const typeDefs = gql`

type Goods {
  _id: ID!
  goods_name: String
  goods_photo: String
  goodsCategoryIds: String
  vendorIds: String
  quantity: Number
}

type Category {
  _id: ID!
  name: String
}

type Vendor {
  _id: ID!
  name: String
  email: String
  phone: String
}

type Query {
  getGoods: [Goods]
}
`
export default typeDefs;
```
- imports/apollo/resolver

```
import { Goods, Vendor, Category, Forward } from '../api/collections';
import { query, addLinks } from '@kaviar/nova';

addLinks(Goods, {
  Vendor: {
    collection: () => Vendor,
    field: "vendorIds",
    many: false,
  },
  Category: {
    collection: () => Category,
    field: "goodsCategoryIds",
    many: false,
  }
});

export default {
  Query: {
    getGoods(_, args, context, info) {
      return query.graphql(Goods, info).fetch();
    }
  }
};
```
- imports/startup/server/index.js
```
import { ApolloServer, gql, makeExecutableSchema } from 'apollo-server-express';
import { WebApp } from 'meteor/webapp'; // Meteor-specific
import { getUser } from 'meteor/apollo'; // specific to Meteor, but you can always check out the Express implementation

// import typeDefs from '../apollo/schema';
import resolvers from '../../apollo/resolver';
import typeDefs from '../../apollo';

const schema = makeExecutableSchema({
  typeDefs,
  resolvers
});

const server = new ApolloServer({
  schema,
  context: async ({ req }) => ({
    user: await getUser(req.headers.authorization)
  }),
});

server.applyMiddleware({
  app: WebApp.connectHandlers,
  cors: true,
  path: '/graphql'
});
```

And the version used is as follows

METEOR@1.12

"@apollo/client": "^3.3.6",
"@babel/runtime": "^7.11.2",
"@kaviar/nova": "^1.3.0",
"apollo-server": "^2.19.0",
"apollo-server-express": "^2.19.0",
"graphql": "^15.4.0",

Please give us a hint that will help us resolve this issue.

**Comment by theodorDiaconu** [comment]
You don't use it on Mongo.Collection, you use it on rawCollection() the
Mongo one.

**Comment by freeseamew** [comment]
Using rawCollection () does the following?

```
import { Goods, Vendor, Category, Forward } from '../api/collections';
import { query, addLinks } from '@kaviar/nova';

const GoodsRaw = Goods.rawCollection();
const VendorRaw = Vendor.rawCollection();
const CatagoryRaw = Category.rawCollection();


addLinks(GoodsRaw, {
  vendor: {
    collection: () => VendorRaw,
    field: "vendorIds",
    // many: false,
  },
  category: {
    collection: () => CatagoryRaw,
    field: "goodsCategoryIds",
    // many: false,
  }
});

export default {
  Query: {
    getGoods(_, args, context, info) {
      return query.graphql(GoodsRaw, info).fetch();
      // return query.graphql()
    }
  }
};

```

But still, the next error is coming up.

```
W20201218-14:33:42.338(9)? (STDERR) /Users/gimgeun-yeong/.meteor/packages/meteor-tool/.1.12.0.1vqv652.8etjg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20201218-14:33:42.489(9)? (STDERR)                                             throw(ex);
W20201218-14:33:42.489(9)? (STDERR)                                             ^
W20201218-14:33:42.489(9)? (STDERR) 
W20201218-14:33:42.489(9)? (STDERR) Error: Cannot find module 'mongodb'
W20201218-14:33:42.489(9)? (STDERR) Require stack:
W20201218-14:33:42.489(9)? (STDERR) - /Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/__tests__/connection.js
W20201218-14:33:42.490(9)? (STDERR) - /Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/__tests__/integration/helpers.js
W20201218-14:33:42.490(9)? (STDERR) - /Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/core/query/hypernova/processVirtualNode.js
W20201218-14:33:42.490(9)? (STDERR) - /Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/core/query/hypernova/storeHypernovaResults.js
W20201218-14:33:42.490(9)? (STDERR) - /Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/core/query/hypernova/hypernova.js
W20201218-14:33:42.498(9)? (STDERR) - /Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/core/query/Query.js
W20201218-14:33:42.499(9)? (STDERR) - /Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/core/api.js
W20201218-14:33:42.499(9)? (STDERR) - /Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/index.js
W20201218-14:33:42.499(9)? (STDERR) - /Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/.meteor/local/build/programs/server/npm-require.js
W20201218-14:33:42.500(9)? (STDERR) - /Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/.meteor/local/build/programs/server/boot.js
W20201218-14:33:42.500(9)? (STDERR) - /Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/.meteor/local/build/main.js
W20201218-14:33:42.500(9)? (STDERR)     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
W20201218-14:33:42.501(9)? (STDERR)     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
W20201218-14:33:42.501(9)? (STDERR)     at Module.require (internal/modules/cjs/loader.js:1025:19)
W20201218-14:33:42.501(9)? (STDERR)     at require (internal/modules/cjs/helpers.js:72:18)
W20201218-14:33:42.502(9)? (STDERR)     at Object.<anonymous> (/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/__tests__/connection.js:4:17)
W20201218-14:33:42.502(9)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1137:30)
W20201218-14:33:42.502(9)? (STDERR)     at Module.Mp._compile (/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/.meteor/local/build/programs/server/runtime.js:50:23)
W20201218-14:33:42.503(9)? (STDERR)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
W20201218-14:33:42.503(9)? (STDERR)     at Module.load (internal/modules/cjs/loader.js:985:32)
W20201218-14:33:42.503(9)? (STDERR)     at Module.Mp.load (/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/.meteor/local/build/programs/server/runtime.js:15:31)
W20201218-14:33:42.504(9)? (STDERR)     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
W20201218-14:33:42.504(9)? (STDERR)     at Module.require (internal/modules/cjs/loader.js:1025:19)
W20201218-14:33:42.504(9)? (STDERR)     at require (internal/modules/cjs/helpers.js:72:18)
W20201218-14:33:42.504(9)? (STDERR)     at Object.<anonymous> (/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/__tests__/integration/helpers.js:4:22)
W20201218-14:33:42.505(9)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1137:30)
W20201218-14:33:42.505(9)? (STDERR)     at Module.Mp._compile (/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/.meteor/local/build/programs/server/runtime.js:50:23) {
W20201218-14:33:42.505(9)? (STDERR)   code: 'MODULE_NOT_FOUND',
W20201218-14:33:42.506(9)? (STDERR)   requireStack: [
W20201218-14:33:42.506(9)? (STDERR)     '/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/__tests__/connection.js',
W20201218-14:33:42.506(9)? (STDERR)     '/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/__tests__/integration/helpers.js',
W20201218-14:33:42.506(9)? (STDERR)     '/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/core/query/hypernova/processVirtualNode.js',
W20201218-14:33:42.506(9)? (STDERR)     '/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/core/query/hypernova/storeHypernovaResults.js',
W20201218-14:33:42.506(9)? (STDERR)     '/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/core/query/hypernova/hypernova.js',
W20201218-14:33:42.506(9)? (STDERR)     '/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/core/query/Query.js',
W20201218-14:33:42.506(9)? (STDERR)     '/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/core/api.js',
W20201218-14:33:42.508(9)? (STDERR)     '/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/node_modules/@kaviar/nova/dist/index.js',
W20201218-14:33:42.509(9)? (STDERR)     '/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/.meteor/local/build/programs/server/npm-require.js',
W20201218-14:33:42.509(9)? (STDERR)     '/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/.meteor/local/build/programs/server/boot.js',
W20201218-14:33:42.509(9)? (STDERR)     '/Users/gimgeun-yeong/Works/Project/Meteor/SAMPLE/meteor-nova/.meteor/local/build/main.js'
W20201218-14:33:42.509(9)? (STDERR)   ]
W20201218-14:33:42.509(9)? (STDERR) }
```

Please show me an example of using nova in a metoer-apollo environment.

**Comment by freeseamew** [comment]
As you told me, I solved the problem using `rawCollection()` as follows.

`Error: Cannot find module 'mongodb'` is due to not doing `'npm i mongo'`

And there's a problem with the query, so I'll ask about this in a new post.

```
import { Items, Vendors, Categories, Forwards } from '../api/collections';
import { query, addLinks, oneToOne, oneToMany, manyToOne, manyToMany  } from '@kaviar/nova';

addLinks(Items.rawCollection(), {
  vendor: {
    collection: () => Vendors.rawCollection(),
    field: "vendorId",
  },
});

addLinks(Vendors.rawCollection(), {
  item: {
    collection: () => Items.rawCollection(),
    inversedBy: "vendor"
  }
})

export default {
  Query: {
    items(_, args, context, info) {
      return query.graphql(Items.rawCollection(), info).fetch();
    },
  },
};
```
